# https://golangci-lint.run/usage/configuration#config-file

linters:
  enable:
    - structcheck
    - varcheck
    - staticcheck
    - unconvert
    - gofmt
    - goimports
    - revive
    - ineffassign
    - vet
    - unused
    - misspell
    - errcheck
    - bodyclose
    - cyclop
    - dogsled
    - nilnil
    - unparam
    - unused
    - nilerr
    - goerr113
  disable:
    - godox

run:
  deadline: 4m
  skip-dirs:
    - misc
