name: E2E Test With Kubernetes

on:
  push:
    branches:
      - "main"
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches: [main]

jobs:
  cri_auth:
    uses: ./.github/workflows/k8s-e2e.yml
    with:
      auth-type: cri

  kubeconf_auth:
    uses: ./.github/workflows/k8s-e2e.yml
    with:
      auth-type: kubeconf
